// angular/src/app/tabs/tabs.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Tab } from '../classes/tab';

@Component({
  selector: 'app-tabs',
  templateUrl: './tabs.component.html',
  styleUrls: ['./tabs.component.css']
})
export class TabsComponent implements OnInit {
  @Input('tabsData')
  tabs: Array<Tab>
  activeTab: number = 0

  constructor() { }

  ngOnInit(): void {
  }

  showTab(index) {
    this.activeTab = index
  }

  trackById(index, item) {
    return Object['uid'](item)
  }
}

<app-tab-button *ngFor="let tab of tabs;trackBy: trackById" tabId="{{tab.id}}" (onActivate)="showTab($event)"></app-tab-button>
<app-tab-content *ngFor="let tab of tabs;trackBy: trackById" tabId="{{tab.id}}" [activeTab]="activeTab" [labelData]="tab.data"></app-tab-content>

// vue/src/components/Tabs.vue
<template>
  <div>
    <app-tab-button v-for="tab in tabs" :key="Object.uid(tab)" :tabId="tab.id" v-on:activate="e => activeTab = e"></app-tab-button>
    <app-tab-content v-for="tab in tabs" :key="Object.uid(tab)" :tabId="tab.id" :activeTab="activeTab" :labelData="tab.data"></app-tab-content>
  </div>
</template>

<script>
export default {
  data() {
    return {
      activeTab: 0
    }
  },
  props: ['tabs']
}
</script>
