// vue/src/components/TabContent.vue
<template>
  <div v-if="activeTab === tabId">
    <app-label v-for="label in labelData" :key="label.id" :tabId="tabId" :labelId="label.id">{{label.name}}</app-label>
  </div>
</template>

<script>
export default {
  data() {
    return {}
  },
  props: ['tabId', 'activeTab', 'labelData']
}
</script>

// angular/src/app/tab-content/tab-content.component.ts
import { Component, OnInit, Input } from '@angular/core';
import { Label } from '../classes/label';
import { Tab } from '../classes/tab';

@Component({
  selector: 'app-tab-content',
  templateUrl: './tab-content.component.html',
  styleUrls: ['./tab-content.component.css']
})
export class TabContentComponent implements OnInit {
  @Input('tabId')
  tabId: number

  @Input('activeTab')
  activeTab: number

  @Input('labelData')
  labelData: Array<Label>

  constructor() {
  }

  ngOnInit(): void {
  }

}

<div *ngIf="activeTab === tabId">
  <app-label *ngFor="let label of labelData" tabId="{{tabId}}" labelId="{{label.id}}">{{label.name}}</app-label>
</div>
